In [1]:
# 导包
import numpy as np

# 1.Numpy的属性介绍

## 1.1 创建ndarray对象

In [2]:
# numpy -> 和数学操作相关的库, numpy的数组是多维的, 并且是固定类型的, numpy的数组是ndarray, 主要用于: 矩阵运算

# 1.机器学习概述. 创建numpy的 ndarray对象.
arr1 =np.arange(15).reshape(3,5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 1.2 演示numpy的常用属性

In [3]:
print(f'numpy的轴: {arr1.ndim}') # 2
print(f'numpy的形状: {arr1.shape}') # (3, 5)
print(f'numpy的元素类型: {arr1.dtype}') # int32
print(f'numpy的元素个数: {arr1.size}') # 15
print(f'numpy的元素字节数: {arr1.itemsize}') # 4
print(f'numpy的元素类型:{type(arr1)}') # <class 'numpy.ndarray'>

numpy的轴: 2
numpy的形状: (3, 5)
numpy的元素类型: int64
numpy的元素个数: 15
numpy的元素字节数: 8
numpy的元素类型:<class 'numpy.ndarray'>


# 2.创建Numpy的ndarray对象

## 2.1 array()函数, 把Python列表 -> ndarray对象

In [4]:
# 1.机器学习概述. 创建python列表对象.
my_list = [11, 22, 33, 44, 55]
print(type(my_list))    #  <class 'list'>

# 2. 把python列表 -> ndarray对象.
arr2 = np.array(my_list)
print(arr2)         # [11 22 33 44 55]
print(type(arr2))   # <class 'numpy.ndarray'>

<class 'list'>
[11 22 33 44 55]
<class 'numpy.ndarray'>


## 2.2 arange()函数, 创建ndarray对象

In [5]:
# arange(起始, 结束, 步长, dtype=类型), 类似于 Python中的range()函数.
# 1.机器学习概述. 创建ndarray对象.
arr3 = np.arange(0, 10, 2, dtype=np.int64) #左开右闭
# 2. 打印ndarray对象.
print(arr3)
print(type(arr3))
print(f'元素的类型: {arr3.dtype}')

[0 2 4 6 8]
<class 'numpy.ndarray'>
元素的类型: int64


## 2.3 随机数生成 ndarray对象

In [6]:
# 1.机器学习概述. random.rand() 生成 0.0 ~ 1.机器学习概述.0之间, 包左不包右的 随机小数矩阵.
arr4 = np.random.rand(3, 5)     # 3行5列
print(arr4)
print(type(arr4))

[[0.4944478  0.59202402 0.5506891  0.96764737 0.37821323]
 [0.0444065  0.98772875 0.99011327 0.68373032 0.27356756]
 [0.63115865 0.26657931 0.01906658 0.66697343 0.35631557]]
<class 'numpy.ndarray'>


In [7]:
# 2. random.randint(起始值, 结束值, size=(行,列)) 生成指定范围, 包左不包右的 随机整数矩阵.
arr5 = np.random.randint(3, 9, size=(2, 6))     # 3 ~ 9之间, 包左不包右. 2行6列
print(arr5)
print(type(arr5))

[[7 5 3 8 8 3]
 [5 5 4 4 7 3]]
<class 'numpy.ndarray'>


In [ ]:
# 3. random.uniform(起始值, 结束值, size=(行,列)) 生成指定范围, 包左不包右的 随机小数矩阵.
arr6 = np.random.uniform(3, 9, size=(2, 6))
print(arr6)
print(type(arr6))

## 2.4 numpy的类型转换 astype()

In [8]:
# 1.机器学习概述. 创建ndarray对象.
arr7 = np.arange(0, 10, 2, dtype=np.int64) #左开右闭
print(arr7)
print(type(arr7))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [9]:
# 2. 把上述的 arr7 ndarray对象的元素 从 int64 转换成 float32.
arr8 = arr7.astype(np.float32)
print(arr8)
print(arr8.dtype)

[0. 2. 4. 6. 8.]
float32


## 2.5 创建等比数列.

In [10]:
# 1.机器学习概述. 创建等比数列 参1:起始值(充当10的指数), 参2:结束值(充当10的指数), 参3:元素个数.
arr9 = np.logspace(0,3,4)
print(arr9)
print(arr9.dtype)

[   1.   10.  100. 1000.]
float64


In [11]:
# 2. 创建等比数列 参1:起始值(充当10的指数), 参2:结束值(充当10的指数), 参3:元素个数. 参4:修改基数.
arr9 = np.logspace(0,3,4,base=2,dtype=np.int64)
print(arr9)
print(arr9.dtype)

[1 2 4 8]
int64


## 2.6 创建等差数列

In [19]:
# 1.机器学习概述 创建等差数列 参1:起始值, 参2:结束值, 参3:元素个数, 参数4:是否包含结束值(默认包含), 参数5:修改基数.
arr10 = np.linspace(1,9,4,endpoint=False,dtype=np.int32)
print(arr10)
print(arr10.dtype)

[1 3 5 7]
int32


# 3.演示Numpy的常用函数

## 3.1 基本函数

In [20]:
# 1.机器学习概述. 创建标准的正态分布的序列.
arr1 = np.random.randn(3,5)
print(arr1)

[[-1.01503214  0.97645077 -1.55465022 -0.02332404 -0.035486  ]
 [ 0.55001824  0.0898256  -0.6727092  -1.38400984 -1.97695591]
 [-1.27172092 -0.05824534 -0.24920721  0.29628955 -0.82738796]]


In [21]:
 #print(np.ceil(arr1)) # 天花板数 -> 向上取整
#print(np.floor(arr1)) # 地板数 -> 向下取整
#print(np.rint(arr1)) # 四舍五入
#print(np.abs(arr1)) # 绝对值
print(np.multiply(arr1,arr1)) # 矩阵乘法
print(arr1 * arr1) # 矩阵相加 效果同上
print(np.where(arr1 >0, 1, -1)) # 条件判断
print(np.isnan(arr1))

[[1.03029024e+00 9.53456107e-01 2.41693731e+00 5.44010997e-04
  1.25925645e-03]
 [3.02520069e-01 8.06863894e-03 4.52537663e-01 1.91548324e+00
  3.90835466e+00]
 [1.61727410e+00 3.39251995e-03 6.21042310e-02 8.77875001e-02
  6.84570840e-01]]
[[1.03029024e+00 9.53456107e-01 2.41693731e+00 5.44010997e-04
  1.25925645e-03]
 [3.02520069e-01 8.06863894e-03 4.52537663e-01 1.91548324e+00
  3.90835466e+00]
 [1.61727410e+00 3.39251995e-03 6.21042310e-02 8.77875001e-02
  6.84570840e-01]]
[[-1  1 -1 -1 -1]
 [ 1  1 -1 -1 -1]
 [-1 -1 -1  1 -1]]
[[False False False False False]
 [False False False False False]
 [False False False False False]]


## 3.2 统计函数

In [23]:
# 1.机器学习概述. 定义ndarray对象
arr1 = np.arange(12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
print(np.cumsum(arr1)) # 累计求和

[ 0  1  3  6 10 15 21 28 36 45 55 66]


In [25]:
print(np.sum(arr1)) # 求和
print(np.sum(arr1,axis=0)) # 列和
print(np.sum(arr1,axis=1)) # 行和


66
[12 15 18 21]
[ 6 22 38]


## 3.3 去重函数

In [26]:
arr1 = np.array([[1,2,1], [2,3,5]])
print(arr1)

[[1 2 1]
 [2 3 5]]


In [27]:
arr2 = np.unique(arr1)
print(f'arr1:{arr1}')
print(f'arr2:{arr2}')

arr1:[[1 2 1]
 [2 3 5]]
arr2:[1 2 3 5]


## 3.4 排序函数

In [28]:
# 1.机器学习概述.定义数组
arr1 = np.array([11,33,22,66,55])
print(arr1)

[11 33 22 66 55]


In [29]:
arr2 = np.sort(arr1)
print(f'arr1:{arr1}')
print(f'arr2:{arr2}')

arr1:[11 33 22 66 55]
arr2:[11 22 33 55 66]


In [30]:
# 3. 通过 数组对象.sort() -> 直接修改数组
print(f'排序前:arr1:{arr1}')
arr1.sort()
print(f'排序后:arr1:{arr1}')

排序前:arr1:[11 33 22 66 55]
排序后:arr1:[11 22 33 55 66]


# 4.Numpy运算

## 4.1 减法运算

In [31]:
arr1 = np.array([10,20,30,40])
arr2 = np.arange(4)
print(f'arr1:{arr1}')
print(f'arr2:{arr2}')

arr1:[10 20 30 40]
arr2:[0 1 2 3]


In [32]:
print(arr1 - arr2) # 矩阵减法

[10 19 28 37]


In [33]:
print(arr1 + arr2) # 矩阵加法

[10 21 32 43]


## 4.2 矩阵乘法

In [34]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
print(f'arr1:{arr1}')
print(f'arr2:{arr2}')


arr1:[[1 2 3]
 [4 5 6]]
arr2:[[1 2 3]
 [4 5 6]]


In [35]:
print(arr1 * arr2)

[[ 1  4  9]
 [16 25 36]]


In [36]:
print(np.multiply(arr1, arr2))

[[ 1  4  9]
 [16 25 36]]


In [37]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[9,8],[6,5],[3,2]])
print(f'arr3:{arr3}')
print(f'arr4:{arr4}')

arr3:[[1 2 3]
 [4 5 6]]
arr4:[[9 8]
 [6 5]
 [3 2]]


In [38]:
#print(arr3 * arr4) #报错,行列数不一致
#(np.multiply(arr3, arr4))#报错,行列数不一致
print(np.dot(arr3, arr4))
print(arr3.dot(arr4)) #效果同上
print(arr3 @ arr4) #效果同上

[[30 24]
 [84 69]]
[[30 24]
 [84 69]]
[[30 24]
 [84 69]]
