In [ ]:
# 导包
import numpy as np

# 1.Numpy的属性介绍

## 1.1 创建ndarray对象

In [ ]:
# numpy -> 和数学操作相关的库, numpy的数组是多维的, 并且是固定类型的, numpy的数组是ndarray, 主要用于: 矩阵运算

# 1. 创建numpy的 ndarray对象.
arr1 =np.arange(15).reshape(3,5)
print(arr1)

## 1.2 演示numpy的常用属性

In [ ]:
print(f'numpy的轴: {arr1.ndim}') # 2
print(f'numpy的形状: {arr1.shape}') # (3, 5)
print(f'numpy的元素类型: {arr1.dtype}') # int32
print(f'numpy的元素个数: {arr1.size}') # 15
print(f'numpy的元素字节数: {arr1.itemsize}') # 4
print(f'numpy的元素类型:{type(arr1)}') # <class 'numpy.ndarray'>

# 2.创建Numpy的ndarray对象

## 2.1 array()函数, 把Python列表 -> ndarray对象

In [ ]:
# 1. 创建python列表对象.
my_list = [11, 22, 33, 44, 55]
print(type(my_list))    #  <class 'list'>

# 2. 把python列表 -> ndarray对象.
arr2 = np.array(my_list)
print(arr2)         # [11 22 33 44 55]
print(type(arr2))   # <class 'numpy.ndarray'>

## 2.2 arange()函数, 创建ndarray对象

In [ ]:
# arange(起始, 结束, 步长, dtype=类型), 类似于 Python中的range()函数.
# 1. 创建ndarray对象.
arr3 = np.arange(0, 10, 2, dtype=np.int64) #左开右闭
# 2. 打印ndarray对象.
print(arr3)
print(type(arr3))
print(f'元素的类型: {arr3.dtype}')

## 2.3 随机数生成 ndarray对象

In [ ]:
# 1. random.rand() 生成 0.0 ~ 1.0之间, 包左不包右的 随机小数矩阵.
arr4 = np.random.rand(3, 5)     # 3行5列
print(arr4)
print(type(arr4))

In [ ]:
# 2. random.randint(起始值, 结束值, size=(行,列)) 生成指定范围, 包左不包右的 随机整数矩阵.
arr5 = np.random.randint(3, 9, size=(2, 6))     # 3 ~ 9之间, 包左不包右. 2行6列
print(arr5)
print(type(arr5))

In [ ]:
# 3. random.uniform(起始值, 结束值, size=(行,列)) 生成指定范围, 包左不包右的 随机小数矩阵.
arr6 = np.random.uniform(3, 9, size=(2, 6))
print(arr6)
print(type(arr6))

## 2.4 numpy的类型转换 astype()

In [ ]:
# 1. 创建ndarray对象.
arr7 = np.arange(0, 10, 2, dtype=np.int64) #左开右闭
print(arr7)
print(type(arr7))

In [ ]:
# 2. 把上述的 arr7 ndarray对象的元素 从 int64 转换成 float32.
arr8 = arr7.astype(np.float32)
print(arr8)
print(arr8.dtype)

## 2.5 创建等比数列.

In [ ]:
# 1. 创建等比数列 参1:起始值(充当10的指数), 参2:结束值(充当10的指数), 参3:元素个数.
arr9 = np.logspace(0,3,4)
print(arr9)
print(arr9.dtype)

In [ ]:
# 2. 创建等比数列 参1:起始值(充当10的指数), 参2:结束值(充当10的指数), 参3:元素个数. 参4:修改基数.
arr9 = np.logspace(0,3,4,base=2,dtype=np.int64)
print(arr9)
print(arr9.dtype)

## 2.6 创建等差数列

In [ ]:
# 1 创建等差数列 参1:起始值, 参2:结束值, 参3:元素个数, 参数4:是否包含结束值(默认包含), 参数5:修改基数.
arr10 = np.linspace(1,10,4,endpoint=False,dtype=np.int32)
print(arr10)
print(arr10.dtype)

# 3.演示Numpy的常用函数

## 3.1 基本函数

In [75]:
# 1. 创建标准的正态分布的序列.
arr1 = np.random.randn(3,5)
print(arr1)

[[ 2.19363082  0.75756308  0.67516289 -1.7362865   0.16913927]
 [ 1.77982656  2.0668218   0.08469306  0.79808253  0.3184954 ]
 [-0.73600993  0.51553679  0.86342674 -0.23384568  1.11861594]]


In [76]:
 #print(np.ceil(arr1)) # 天花板数 -> 向上取整
#print(np.floor(arr1)) # 地板数 -> 向下取整
#print(np.rint(arr1)) # 四舍五入
#print(np.abs(arr1)) # 绝对值
print(np.multiply(arr1,arr1)) # 矩阵乘法
print(arr1 * arr1) # 矩阵相加 效果同上
print(np.where(arr1 >0, 1, -1)) # 条件判断
print(np.isnan(arr1))

[[4.81201619 0.57390182 0.45584493 3.01469082 0.02860809]
 [3.1677826  4.27175235 0.00717291 0.63693572 0.10143932]
 [0.54171062 0.26577818 0.74550574 0.0546838  1.25130163]]
[[4.81201619 0.57390182 0.45584493 3.01469082 0.02860809]
 [3.1677826  4.27175235 0.00717291 0.63693572 0.10143932]
 [0.54171062 0.26577818 0.74550574 0.0546838  1.25130163]]
[[ 1  1  1 -1  1]
 [ 1  1  1  1  1]
 [-1  1  1 -1  1]]
[[False False False False False]
 [False False False False False]
 [False False False False False]]


## 3.2 统计函数

In [ ]:
# 1. 定义ndarray对象
arr1 = np.arange(12).reshape(3,4)
print(arr1)

In [ ]:
print(np.cumsum(arr1)) # 累计求和

In [ ]:
print(np.sum(arr1)) # 求和
print(np.sum(arr1,axis=0)) # 列和
print(np.sum(arr1,axis=1)) # 行和


## 3.3 去重函数

In [ ]:
arr1 = np.array([[1,2,1], [2,3,5]])
print(arr1)

In [ ]:
arr2 = np.unique(arr1)
print(f'arr1:{arr1}')
print(f'arr2:{arr2}')

## 3.4 排序函数

In [ ]:
# 1.定义数组
arr1 = np.array([11,33,22,66,55])
print(arr1)

In [ ]:
arr2 = np.sort(arr1)
print(f'arr1:{arr1}')
print(f'arr2:{arr2}')

In [ ]:
# 3. 通过 数组对象.sort() -> 直接修改数组
print(f'排序前:arr1:{arr1}')
arr1.sort()
print(f'排序后:arr1:{arr1}')

# 4.Numpy运算

## 4.1 减法运算

In [ ]:
arr1 = np.array([10,20,30,40])
arr2 = np.arange(4)
print(f'arr1:{arr1}')
print(f'arr2:{arr2}')

In [ ]:
print(arr1 - arr2) # 矩阵减法

In [ ]:
print(arr1 + arr2) # 矩阵加法

## 4.2 矩阵乘法

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
print(f'arr1:{arr1}')
print(f'arr2:{arr2}')


In [ ]:
print(arr1 * arr2)

In [ ]:
print(np.multiply(arr1, arr2))

In [ ]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[9,8],[6,5],[3,2]])
print(f'arr3:{arr3}')
print(f'arr4:{arr4}')

In [ ]:
#print(arr3 * arr4) #报错,行列数不一致
#(np.multiply(arr3, arr4))#报错,行列数不一致
print(np.dot(arr3, arr4))
print(arr3.dot(arr4)) #效果同上
print(arr3 @ arr4) #效果同上